function [ labels ] = getLabels12Leads()
%GETLABELS12LEADS Gets a 12-cell with the 12-leads standard labels (I, II, III, aVR, ..., V1, ..., V6)


    labels = { ...
		'I',   'II',  'III', ...
		'aVR', 'aVL', 'aVF', ...
		'V1',  'V2',  'V3',  ...
		'V4',  'V5',  'V6' };
	
end

